### ISSUE TITLE
Allow overriding structs to have different string casing

### ISSUE THREAD

**Issue by mitar** [ldez/tagliatelle#24] opened 2024-01-28 21:20 UTC
In my code I am using JSON from different sources so I have structs with json tags of different string casings. It would be great if one could override expected string case by struct or at least a file (by package which I saw in other issues is not enough for me).

**Comment by ldez** [comment] 2024-01-28 21:21
duplicate of #3

**Closed by ldez** 2024-01-28 21:21 UTC
Labels: duplicate

**Comment by mitar** [comment] 2024-01-28 21:41
#3 is per sub-package, but in my case I have multiple different structs inside the same package. So something like a comment would be great to be able to configure that. Or some per-file config or something.

**Comment by ldez** [comment] 2024-01-28 22:29
It's unexpected to have different conventions inside the same package:
- if the structures are part of the same project ("internal" API mapping) then the convention should be the same.
- if the structures are "external" API mapping then it's better to have a dedicated package by API source.

The support of convention by package, because a project uses different API sources, will be supported.
But I don't want to enforce multiple conventions inside a package because this is bad practice.

**Comment by mitar** [comment] 2024-01-28 22:39
It is not uncommon. For example, I am making [OpenID Connect system](https://gitlab.com/charon/charon) and for my own API I control I want camelCase, but OpenID Spec for one JSON response [requires snake_case](https://gitlab.com/charon/charon/-/blob/main/oidc_configuration.go?ref_type=heads#L13). Why would I have to move just that one struct into another package? It is only one struct, but I do not control the case. Still, it would be great to lint to make sure I didn't make any mistake.

**Comment by ldez** [comment] 2024-01-28 22:55
> It is not uncommon.

The problem is not whether this is common or not, it's a bad practice to have several conventions inside the same package because it leads to maintenance problems.

> It is only one struct, but I do not control the case. 

Your use case is niche, and as a global feature will lead to enforcing bad practices.
For me, the best approach is still to isolate external things: this creates clear documentation and eases maintenance.
But I understand your use case, in this situation, I think I would just ignore the structure.

For now, I don't plan to support per-structure configuration.
